{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Production state (past hour)",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "pasteurize:monitoring:production_state:overview:Stop:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Filling:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Heating:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Emptying:duration"
    }
   ]
  },
  {
   "title": "Production state (past hour)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "pasteurize:monitoring:production_state:overview:Stop:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Filling:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Heating:duration"
    },
    {
     "target": "pasteurize:monitoring:production_state:overview:Emptying:duration"
    }
   ]
  },
  {
   "title": "Tank Liquid Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "target": "pasteurize:monitoring:tank_liquid_temperature"
    }
   ]
  },
  {
   "title": "Tank Liquid Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "pasteurize:monitoring:tank_liquid_level"
    }
   ]
  }
 ]
}