{
 "title": "Dashboard Demo ImplicixDB",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pie Chart example",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "system:metrics:electrical:heat_service_state:_10Minutes:Disabled:duration"
    },
    {
     "target": "system:metrics:electrical:heat_service_state:_10Minutes:StandBy:duration"
    },
    {
     "target": "system:metrics:electrical:heat_service_state:_10Minutes:Running:duration"
    },
    {
     "target": "system:metrics:electrical:heat_service_state:_10Minutes:Other:duration"
    },
    {
     "target": "system:metrics:electrical:heat_service_state:_10Minutes:Failure:duration"
    }
   ]
  },
  {
   "title": "Bar chart example",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "system:metrics:heat:heating_energy:_1Minutes"
    },
    {
     "target": "system:metrics:gas:gas_index:_1Minutes"
    }
   ]
  },
  {
   "title": "Time series example",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "system:metrics:compressor:compressor_time:_5Seconds"
    },
    {
     "target": "system:metrics:heat:dhw_energy:_1Minutes"
    },
    {
     "target": "system:metrics:heat:heating_energy:_1Minutes"
    }
   ]
  }
 ]
}